- name: Clone git repo with containers
  ansible.builtin.git:
    repo: 'https://github.com/sabaroof/cisco-live-2022.git'
    dest: /root/github/

- name: Configure IP for frontend interface
  ansible.builtin.command: "ip addr add '{{ prodvm_frontend_ip }}' dev '{{ prodvm_frontend_int }}'"
  register: output
  changed_when: output.rc != 0

- name: Standup int for frontend interface
  ansible.builtin.command: "ip link set '{{ prodvm_frontend_int }}' up"
  register: output
  changed_when: output.rc != 0

- name: Configure IP for backend interface
  ansible.builtin.command: "ip addr add '{{ prodvm_backend_ip }}' dev '{{ prodvm_backend_int }}'"
  register: output
  changed_when: output.rc != 0

- name: Standup int for backend interface
  ansible.builtin.command: "ip link set '{{ prodvm_backend_int }}' up"
  register: output
  changed_when: output.rc != 0

- name: Configure IP for db interface
  ansible.builtin.command: "ip addr add '{{ prodvm_db_ip }}' dev '{{ prodvm_db_int }}'"
  register: output
  changed_when: output.rc != 0

- name: Standup int for db interface
  ansible.builtin.command: "ip link set '{{ prodvm_db_int }}' up"
  register: output
  changed_when: output.rc != 0

- name: Run compose
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: /root/github/ciscolive-containers
  register: output
  changed_when: output.rc != 0  