- name: Attaching cloud tenant to an on prem site
  cisco.mso.mso_tenant_site:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    tenant: '{{ ndo_tenant }}'
    site: '{{ ndo_site_onprem }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Associate the on prem site with the template
  cisco.mso.mso_schema_site:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    site: '{{ ndo_site_onprem }}'
    template: '{{ ndo_template }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Configure the template to deploy the BDs
  cisco.mso.mso_schema_template_bd:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    bd: '{{ item }}'
    vrf:
      name: '{{ ndo_vrf }}'
    state: present
    validate_certs: no
  loop: '{{ ["{{ndo_bd_frontend}}", "{{ndo_bd_backend}}", "{{ndo_bd_db}}"] }}'
  delegate_to: localhost

- name: Configure the template to deploy the frontend subnet
  cisco.mso.mso_schema_template_bd_subnet:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    bd: '{{ ndo_bd_frontend }}'
    subnet: '{{ndo_bd_frontend_gw}}/{{ndo_bd_frontend_gw_mask}}'
    state: present
    scope: public
    validate_certs: no 
  delegate_to: localhost

- name: Configure the template to deploy the backend subnet
  cisco.mso.mso_schema_template_bd_subnet:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    bd: '{{ ndo_bd_backend }}'
    subnet: '{{ndo_bd_backend_gw}}/{{ndo_bd_backend_gw_mask}}'
    state: present
    scope: public
    validate_certs: no
  delegate_to: localhost

- name: Configure the template to deploy the db subnet
  cisco.mso.mso_schema_template_bd_subnet:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    bd: '{{ ndo_bd_db }}'
    subnet: '{{ndo_bd_db_gw}}/{{ndo_bd_db_gw_mask}}'
    state: present
    scope: public
    validate_certs: no
  delegate_to: localhost

- name: Create frontend EPG
  cisco.mso.mso_schema_template_anp_epg:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_frontend }}'
    bd:
      name: '{{ ndo_bd_frontend }}'
    vrf:
      name: '{{ ndo_vrf }}'
    state: present
    validate_certs: no  
  delegate_to: localhost

- name: Create backend EPG
  cisco.mso.mso_schema_template_anp_epg:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_backend }}'
    bd:
      name: '{{ ndo_bd_backend }}'
    vrf:
      name: '{{ ndo_vrf }}'
    state: present
    validate_certs: no   
  delegate_to: localhost

- name: Create db EPG
  cisco.mso.mso_schema_template_anp_epg:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_db }}'
    bd:
      name: '{{ ndo_bd_db }}'
    vrf:
      name: '{{ ndo_vrf }}'
    state: present
    validate_certs: no  
  delegate_to: localhost

- name: Attach the VMM domain to the created EPGs
  cisco.mso.mso_schema_site_anp_epg_domain:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    site: '{{ ndo_site_onprem }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ item }}'
    domain_association_type: vmmDomain
    domain_profile: '{{ ndo_vmm }}'
    deployment_immediacy: immediate
    resolution_immediacy: immediate
    enhanced_lagpolicy_name: '{{ ndo_lag }}'
    enhanced_lagpolicy_dn: 'uni/vmmp-VMware/dom-{{ndo_vmm}}/vswitchpolcont/enlacplagp-{{ndo_lag}}'
    state: present
    validate_certs: no
  loop: '{{ ["{{ ndo_epg_frontend }}", "{{ ndo_epg_backend }}", "{{ ndo_epg_db }}"] }}'
  delegate_to: localhost

- name: Add a selector to cloud site frontend EPG
  cisco.mso.mso_schema_site_anp_epg_selector:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    site: '{{ ndo_site_cloud }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_frontend }}'
    selector: selector_frontend
    expressions:
      - type: ip_address
        operator: equals
        value: '{{ ndo_bd_frontend_subnet_cloud }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a selector to cloud site backend EPG
  cisco.mso.mso_schema_site_anp_epg_selector:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    site: '{{ ndo_site_cloud }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_backend }}'
    selector: selector_backend
    expressions:
      - type: ip_address
        operator: equals
        value: '{{ ndo_bd_backend_subnet_cloud }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a selector to cloud site DB EPG
  cisco.mso.mso_schema_site_anp_epg_selector:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    site: '{{ ndo_site_cloud }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_db }}'
    selector: selector_db
    expressions:
      - type: ip_address
        operator: equals
        value: '{{ ndo_bd_db_subnet_cloud }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a new contract filter
  cisco.mso.mso_schema_template_contract_filter:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    contract: '{{ ndo_contract }}'
    contract_scope: vrf
    filter: '{{ ndo_filter }}'
    action: permit
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a new filter entry
  cisco.mso.mso_schema_template_filter_entry:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    filter: '{{ ndo_filter }}'
    entry: '{{ ndo_filter_entry }}'
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a contract to a frontend EPG
  cisco.mso.mso_schema_template_anp_epg_contract:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_frontend }}'
    contract:
      name: '{{ ndo_contract }}'
      type: consumer
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a contract to a backend EPG
  cisco.mso.mso_schema_template_anp_epg_contract:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_backend }}'
    contract:
      name: '{{ ndo_contract }}'
      type: provider
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a contract to a backend EPG
  cisco.mso.mso_schema_template_anp_epg_contract:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_backend }}'
    contract:
      name: '{{ ndo_contract }}'
      type: consumer
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Add a contract to a db EPG
  cisco.mso.mso_schema_template_anp_epg_contract:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    anp: '{{ ndo_anp }}'
    epg: '{{ ndo_epg_db }}'
    contract:
      name: '{{ ndo_contract }}'
      type: provider
    state: present
    validate_certs: no
  delegate_to: localhost

- name: Deploy a schema template
  cisco.mso.mso_schema_template_deploy:
    host: '{{ ndo_host }}'
    username: '{{ ndo_creds.user }}'
    password: '{{ ndo_creds.pass }}'
    schema: '{{ ndo_schema }}'
    template: '{{ ndo_template }}'
    state: deploy
    validate_certs: no
  delegate_to: localhost