- name: A Playbook for Task4 - stretching the tenant
  hosts: ndo
  gather_facts: false
  connection: httpapi

  roles:
    - cloud-tenant-stretch

- name: A Playbook for Task2 Step3 - migrating the containers to the stretched tenant
  hosts: vcenter
  gather_facts: false
  connection: httpapi

  roles:
    - { role: vm-pg-attachment, vm: prod, service: frontend }
    - { role: vm-pg-attachment, vm: prod, service: backend }
    - { role: vm-pg-attachment, vm: prod, service: db }
    - { role: vm-pg-attachment, vm: test, service: frontend }