- name: Create a BD for the backend tier
  cisco.aci.aci_bd:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    vrf: '{{ apic_vrf }}'
    bd: '{{ apic_bd_backend }}'
    validate_certs: no
    state: present

- name: Create a BD for the db tier
  cisco.aci.aci_bd:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    vrf: '{{ apic_vrf }}'
    bd: '{{ apic_bd_db }}'
    validate_certs: no
    state: present

- name: Create backend subnet
  cisco.aci.aci_bd_subnet:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    bd: '{{ apic_bd_backend }}'
    subnet_name: '{{ apic_bd_backend_subnet_name }}'
    gateway: '{{ apic_bd_backend_gw }}'
    mask: '{{ apic_bd_backend_gw_mask }}'
    validate_certs: no
    state: present

- name: Create db subnet
  cisco.aci.aci_bd_subnet:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    bd: '{{ apic_bd_db }}'
    subnet_name: '{{ apic_bd_db_subnet_name }}'
    gateway: '{{ apic_bd_db_gw }}'
    mask: '{{ apic_bd_db_gw_mask }}'
    validate_certs: no
    state: present

- name: Create an AP
  cisco.aci.aci_ap:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    ap: '{{ apic_ap }}'
    validate_certs: no
    state: present  

- name: Create backend EPG
  cisco.aci.aci_epg:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    bd: '{{ apic_bd_backend }}'
    ap: '{{ apic_ap }}'
    epg: '{{ apic_epg_backend }}'
    validate_certs: no
    state: present

- name: Create db EPG
  cisco.aci.aci_epg:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    bd: '{{ apic_bd_db }}'
    ap: '{{ apic_ap }}'
    epg: '{{ apic_epg_db }}'
    validate_certs: no
    state: present  

- name: Attach the VMM domain to the created EPGs
  cisco.aci.aci_epg_to_domain:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    ap: '{{ apic_ap }}'
    epg: '{{ apic_epg_backend }}'
    domain: '{{ apic_vmm }}'
    domain_type: vmm
    vm_provider: vmware
    enhanced_lag_policy: '{{ apic_lag }}'
    validate_certs: no

- name: Attach the VMM domain to the created EPGs
  cisco.aci.aci_epg_to_domain:
    host: '{{ apic_host }}'
    username: '{{ apic_creds.user }}'
    password: '{{ apic_creds.pass }}'
    tenant: '{{ apic_tenant }}'
    ap: '{{ apic_ap }}'
    epg: '{{ apic_epg_db }}'
    domain: '{{ apic_vmm }}'
    domain_type: vmm
    vm_provider: vmware
    enhanced_lag_policy: '{{ apic_lag }}'
    validate_certs: no
