vc_creds: {user: "aciadmin@vsphere.local", pass: "{{ vc_user01 }}"}
vc_host: 198.19.202.251
vc_datacenter: NYC
vc_prodvm: CLUS_User01_ProdVM
vc_prodvm_mac: 00:50:56:ad:0f:83
vc_prodvm_int: ens161
vc_prodvm_mgmt_ip: 198.19.202.5
vc_testvm: CLUS_User01_TestVM
vc_testvm_mac: 00:50:56:ad:8c:75
vc_pg: CLUS-user01|CLUS_user01_AP|EPG_Singlepage